// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC_ewRrzQnTqIJS3053SeZZkYKIv4xQ3Z0',
    appId: '1:216830360220:web:801a9087994b09a00acb59',
    messagingSenderId: '216830360220',
    projectId: 'mine-note-cda71',
    authDomain: 'mine-note-cda71.firebaseapp.com',
    storageBucket: 'mine-note-cda71.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDXuqwVTYzsm-SkohWOYzRDAfVBUC99FVQ',
    appId: '1:216830360220:android:8999774f964ca2820acb59',
    messagingSenderId: '216830360220',
    projectId: 'mine-note-cda71',
    storageBucket: 'mine-note-cda71.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA705OoRddvF1yLiEApQKV3WVDinbDSqPc',
    appId: '1:216830360220:ios:a89e6fcf32fb0e790acb59',
    messagingSenderId: '216830360220',
    projectId: 'mine-note-cda71',
    storageBucket: 'mine-note-cda71.appspot.com',
    iosClientId: '216830360220-4pjbomdadt0t864hg8be6rvuot3i40p8.apps.googleusercontent.com',
    iosBundleId: 'com.example.mineNotes',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA705OoRddvF1yLiEApQKV3WVDinbDSqPc',
    appId: '1:216830360220:ios:a89e6fcf32fb0e790acb59',
    messagingSenderId: '216830360220',
    projectId: 'mine-note-cda71',
    storageBucket: 'mine-note-cda71.appspot.com',
    iosClientId: '216830360220-4pjbomdadt0t864hg8be6rvuot3i40p8.apps.googleusercontent.com',
    iosBundleId: 'com.example.mineNotes',
  );
}
